### ISSUE TITLE
also use \lc fields in check script

### ISSUE THREAD

**Issue by IrenH** [dictionaria/pydictionaria#15]
a \cf field may link back to \lx as well as \lc (cf. daakaka), currently this pops up as an error once the check script is run, but it isn't one

**Comment by xrotwang** [comment]
Hm. That's a new requirement. Is `\lc` somewhat standard - or would this have to be configurable?

**Comment by IrenH** [comment]
\lc = lexical citation form is a standarf MDF field, used in Toolbox as well as FLEx, It is most often used in root dictionaries, but also in others

**Comment by xrotwang** [comment]
Ok. So it would make sense to add `\lc` in general as a possible target for relation fields.

**Comment by IrenH** [comment]
Yes, it would :) thank you!
