### ISSUE TITLE
xlrd.biffh.XLRDError: Excel xlsx file; not supported

### ISSUE THREAD

**Issue by johenglisch** [dictionaria/pydictionaria#25]
Exception occurs in test:

https://github.com/dictionaria/pydictionaria/blob/9a16ae87c0e43ef23ccebe160c89ac4fbc4628ba/tests/test_commands.py#L25-L26

Apparently, [xlrd dropped xlsx support](https://groups.google.com/g/python-excel/c/IRa8IWq_4zk/m/Af8-hrRnAgAJ).

Two options:
 1. Switch to `openpyxl`
 2. Drop Excel support entirely -- none of the submissions use it

**Comment by xrotwang** [comment]
Option 2 sounds attractive!

**Comment by johenglisch** [comment]
Yup, that is my favourite as well. (^^)
While we're at it -- `formats/filemaker.py` is not used anywhere either.  Should we just get rid of that, too?

**Comment by xrotwang** [comment]
There used to be the Pite Saami dictionary. Is this gone?

**Comment by johenglisch** [comment]
We don't have any Saami dicts.

btw, the code looks for a `FIELDS.txt`, which none of the submissions have

https://github.com/dictionaria/pydictionaria/blob/9a16ae87c0e43ef23ccebe160c89ac4fbc4628ba/src/pydictionaria/formats/filemaker.py#L33-L35

**Comment by xrotwang** [comment]
Ok, the project seems to have ended, see https://saami.uni-freiburg.de/psdp/ordbok/home.php

**Comment by xrotwang** [comment]
I guess it's enough if that code lives on in the git history :)

**Comment by johenglisch** [comment]
done (^^)
