### ISSUE TITLE
CLDF conversion of \cf field

### ISSUE THREAD

**Issue by xrotwang** [dictionaria/pydictionaria#5]
For Tseltal, the `\cf` field contains almost exclusively (sometimes several) lexeme IDs. And I think this is what we should require; i.e. no additional text like *quizás relacionado con* - as the [submission guide](https://dictionaria.clld.org/submit#entry) explains:

> Finally, an entry can contain (standard or language-specific) association fields, i.e. fields that establish a relationship between the entry and some other entry. The content of an association field is a list of entry IDs. 

Under this assumption the most appropriate equivalent in the CLDF data would be a column 
```python
{
    "name": "See_Also",
    "separator": " ; "
}
```
which references `EntryTable`, i.e. is specified in the [`foreignKeys` attribute](https://www.w3.org/TR/tabular-metadata/#foreign-key-reference-between-tables) of the table:
```python
    "foreignKeys": [{
        "columnReference": "See_Also",
        "reference": {
            "resource": "entries.csv",
            "columnReference": "ID"
        }
    }]
```

**Comment by xrotwang** [comment]
Note: Currently, the `\cf` field is converted to a text field with embedded markdown links. This is not ideal, because it "hides" the relations from the database, which means the database cannot enforce integrity, and the links are not available for automated processing (without parsing the markdown).

**Comment by xrotwang** [comment]
Note that explicitly adding the foreign key constraint in the CLDF metadata makes it possible to check referential integrity running `cldf validate cldf-metadata.json`.

**Comment by xrotwang** [comment]
Btw.: @IrenH  For tseltal, this would require editing just a handful of `\cf` fields (given below with line numbers in `entries.csv`):
```
180  [xux](LX007864) @
195  [alal](LX000209) (sentido más general de 'niño, bebé')
2143 [juju'ajk'](LX002722) (forma distributiva)
3969 Tenejapa [jlo'il](LX002509)
4679 para especificar 'hija' por oposición a 'hijo' [antsil nich'an](LX000269)
6343 [tsalub](LX006554) (específicamente para pollos)
7732 quizás relacionado con [koltay](LX003373)
```

**Comment by IrenH** [comment]
is it a good idea to change anything in the .csv file directly? these are created ad hoc and any changes would have to be made again and again upon re-processing.. maybe it would be better to make changes in the db.sfm file? what would I have to do there? thanks!

**Comment by xrotwang** [comment]
No, of course not. I only searched for the relevant entries in the csv, because that's easier to do. The edits should be done in the `db.sfm`.

**Comment by xrotwang** [comment]
You search for ` @` in a value for `\cf` and remove it, etc.

**Comment by IrenH** [comment]
Okay, thanks! will do!

**Comment by IrenH** [comment]
I found 3 @'s in the file and removed them

**Comment by xrotwang** [comment]
Good. So that took care of the first line in the above cases. Next up are:
```
195  [alal](LX000209) (sentido más general de 'niño, bebé')
2143 [juju'ajk'](LX002722) (forma distributiva)
3969 Tenejapa [jlo'il](LX002509)
4679 para especificar 'hija' por oposición a 'hijo' [antsil nich'an](LX000269)
6343 [tsalub](LX006554) (específicamente para pollos)
7732 quizás relacionado con [koltay](LX003373)
```

**Comment by IrenH** [comment]
there are no more @'s what is wrong with these?

**Comment by xrotwang** [comment]
The task is to remove all **non-lexeme ID content** in `\cf` fields. So
```
195  [alal](LX000209) (sentido más general de 'niño, bebé')
```
means, there's a line
```
\cf TSEXXXX (sentido más general de 'niño, bebé')
```
in `db.sfm`, and the `(sentido más general de 'niño, bebé')` should be removed.

**Comment by IrenH** [comment]
hmm... I see... that would be more than a handful of cases....
e.g in the entry:
\lxid TSE01701
\lx al
\hm 2
\ps n2.
...
\cf para especificar sexo TSE02401, TSE30421
\cf TSE01821 (sentido más general de 'niño, bebé')

there are two \cf fields and the first one also has non ID info, but does not show up in your above list...
so we need to lose the info?

**Comment by IrenH** [comment]
done

**Comment by xrotwang** [comment]
Multiple `\cf` fields not being merged seems to be a bug of the CLDF conversion. @johenglisch can you confirm?

And yes, we'd lose information - unless we put this information somewhere else.

**Comment by IrenH** [comment]
I have deleted all extra info.. wasn't that much after all and the info is basically there in the entries it was referred to, so that's okay
