### ISSUE TITLE
Contents of markers appearing multiple times must be concatenated for CLDF conversion

### ISSUE THREAD

**Issue by xrotwang** [dictionaria/pydictionaria#9]
See also #5

**Comment by IrenH** [comment]
would this also pertain to Palula, where we find things like:
\va variant1
\ve EnglishofVariant1
\va variant 2
\ve EnglishofVariant2
where \ve always refers to the preceding \va?
this might actually help! if the information stays in the correct order:
variant1 ; variant2
EnglishofVariant1 ; EnglishofVariant2

**Comment by xrotwang** [comment]
Palula has all sorts of implicit marker hierarchies and significant orderings, see https://github.com/clld/dictionaria-intern/blob/master/submissions-internal/palula/__init__.py

This is why I implemented a [pre-processing](https://github.com/clld/dictionaria-intern/blob/0d6914d467b76694f5ba74b4e3c7cfddbd4670ed/submissions-internal/palula/__init__.py#L45). If this step is still active, it will "inlined" the `\ve` content in `\va`, resulting in
```
\va variant1 (EnglishofVariant1)
...
```

**Comment by IrenH** [comment]
okay, great!! can this also be applied to \bw and \bwv ?
